import fs from 'node:fs';
const media=JSON.parse(fs.readFileSync('../../outputs/case-study-media.json','utf8'));
const selections=[
 ['rory','Confess your marketing sins to AI Rory','Live experiences','rory-sutherland','rory-', 'pl3mb34ZxRg'],
 ['live-hosts','A conversation with the whole conference','Live experiences','famous-ai','ltw-','v1hy3UyTWuM'],
 ['international','Your first interview, with room to practise','Live experiences','sdaia-','6a5b7afd','qfdZtaxYOF0'],
 ['oman','AI video for a national election','Live experiences','oman-digital','oman-election|6a5b7afe','CJGsZMNTwOo'],
 ['research','Making aviation data understandable','Enterprise engineering','abu-dhabi','ada-',null]
];
const records=selections.map(([id,title,category,slug,match,video])=>{
 const source=media.find(m=>m.source.includes(slug));
 const images=source.image_candidates.filter(i=>new RegExp(match).test(i.src));
 return {id,title,category,video,images,legacy:true,note:id==='research'?'Illustrative images only. The source identifies these as AI-generated concepts, not photographs or screenshots of the deployment.':id==='international'?'Publisher video: “AI Interview Rough Cut”.':''};
});
records.push(
 {id:'good-omen',title:'Two products. Twenty hours. First place.',category:'Hackathon wins',role:'Good Omen team: Aaron Jones, Giovanni Funchal and Marko Stapfner',body:[['The challenge','At Project Europe × Lovable in Stockholm, our team built a journalist avatar and a real-time video tool in under twenty hours.'],['What happened','Good Omen won the competition. Impact Loop acquired the journalist tool, giving the project a life beyond the hackathon.'],['Why it matters','This is the kind of work I enjoy: a demanding brief, a small team and a working product people can actually use.']],links:[['Impact Loop’s account','https://www.impactloop.com/artikel/impact-loop-s-avatar-idea-wins-at-lovable-and-project-europe-hackathon'],['Watch my Video Moonshot demo post','https://www.linkedin.com/posts/aaronbenjaminjones_goodomen-ai-video-activity-7365483054498209794-qXtD']]},
 {id:'ai-engine',title:'Good Omen takes the overall win',category:'Hackathon wins',role:'With Giovanni Funchal and Marko Stapfner',body:[['The project','Our Good Omen team built Summer Chat, a conversational AI project, at the AI Engine Summer Hack.'],['The result','The organiser named Summer Chat the overall winner. That collaboration continued into our Stockholm hackathon entry.']],links:[['Organiser’s results and photographs','https://jamesin.substack.com/p/summer-hack']]},
 {id:'storymachine',title:'More time creating. Less time waiting.',category:'Products',role:'StoryMachine / Product building and real-time creative AI',body:[['What I’m building','I’m building StoryMachine so people can explore creative directions together, with agents helping them research, plan and visualise their ideas.'],['Why it matters','Fast generation is only part of the problem. People need a way to develop a story, compare possibilities and decide what is worth making. My work connects those creative decisions to the technology.']],links:[]},
 {id:'open-source',title:'The engineering behind the experience',category:'Open source',role:'Public projects and research engineering',body:[['Avatar infrastructure','My public soulx-livekit-avatar project brings together talking-head avatars and real-time conversation infrastructure.'],['Research in practice','I also maintain a collection of real-time video generation resources. These repositories let you inspect the work behind the demos.']],links:[['Explore soulx-livekit-avatar','https://github.com/yepicaiaaron/soulx-livekit-avatar'],['Real-time video resources','https://github.com/yepicaiaaron/awesome-realtime-video-generation']]},
 {id:'ai-consulting',title:'Helping a team become capable with AI',category:'Consulting',role:'Lead AI engineering consultant / General Purpose',images:[{src:'assets/saudi-speaking.jpeg',alt:'Aaron speaking on stage. Speaking photograph, not a client training session.'}],body:[['Where we start','I help leaders work out where AI could make a difference, what to do first and how to bring their people with them.'],['What I do','Alongside strategy and executive coaching, I teach teams to use tools such as Claude Code, build agents and apply them to their own work. The goal is to leave people capable of taking the next step themselves.']],links:[]},
 {id:'fikay',title:'A business that helped families earn',category:'Earlier ventures',role:'Founder / Fikay Fashion',body:[['The beginning','After volunteering in Cambodia, I wanted to help parents earn a living so their children could stay in education. Fikay made fashion accessories from recycled materials, working with local producers.'],['Recognition','I received the British Empire Medal in 2016 for services to ethical fashion, and the University of Essex named me Alumnus of the Year in 2018.']],links:[['University of Essex profile','https://www.essex.ac.uk/alumni/awards/alumnus-of-the-year/2018']]},
 {id:'seefashion',title:'Helping people discover what they love',category:'Earlier ventures',role:'Founder / SeeFashion',body:[['The product','With SeeFashion, I worked on computer vision and machine learning for personalised shopping and product discovery.'],['The connection','The question that interested me was how technology could understand what someone was looking for and make the experience more useful to them.']],links:[['University of Essex profile','https://www.essex.ac.uk/alumni/awards/alumnus-of-the-year/2018']]},
 {id:'creative-community',title:'Getting filmmakers and engineers building together',category:'Creative communities',role:'Big Screen Hack / Organising creative collaboration',images:[{src:'assets/bsh-film-card.jpg',alt:'Big Screen Hack project image'}],body:[['The idea','Bring filmmakers and AI builders into the same room, give them a deadline and make something people can watch.'],['What I take from it','These collaborations inform how I build creative tools: what helps a team find a direction, where the workflow gets in the way and what people need to finish.']],links:[['Big Screen Hack event','https://luma.com/mah1xx07']]}
);
fs.writeFileSync('dist/js/collection-data.js','window.portfolioCollection='+JSON.stringify(records)+';');
