import fs from 'node:fs';
import vm from 'node:vm';
// Preserve Aaron's existing interview accounts without requiring the old slides.
const scope={window:{}};
const source=fs.readFileSync('dist/js/case-stories.js','utf8');
vm.runInNewContext(source.split(' // Oman gets')[0]+'window.accounts=cases;})();',scope);
const dataScope={window:{}};
vm.runInNewContext(fs.readFileSync('dist/js/collection-data.js','utf8'),dataScope);
const records=dataScope.window.portfolioCollection;
for(const item of records){if(scope.window.accounts[item.id]){const a=scope.window.accounts[item.id];item.role=a.role;item.body=a.beats;delete item.legacy}}
const byId=id=>records.find(r=>r.id===id);
byId('good-omen').images=[{src:'assets/good-omen-stockholm.jpg',alt:'Good Omen with Impact Loop in Stockholm. Photograph: Jesper Andersson / Impact Loop.'}];
byId('ai-engine').images=[{src:'assets/good-omen-summer.jpeg',alt:'Good Omen presenting at the AI Engine Summer Hack. Photograph: Adam Isfendiyar.'}];
byId('fikay').images=[{src:'assets/aaron-fikay.jpg',alt:'Aaron Jones in the University of Essex Alumnus of the Year profile.'}];
Object.assign(byId('creative-community'),{title:'Give people space. They’ll surprise you.',role:'Big Screen Hack / Bringing filmmakers, engineers and partners together',video:'UZgBSVi-kpc',images:[{src:'assets/lilies-film.jpg',alt:'lilies — Muja Studios / Jabir Mohammed. Big Screen Hack Cannes, Film Track 1st / Best in Show.'}],note:'Participant film: lilies, by Muja Studios / Jabir Mohammed. My role was organising the event, not making this film. The Cinéum screening was an independent event during Cannes festival week.',body:[['Why make space for creativity?','An unfamiliar tool can be intimidating on your own. In a room with people who share what they know, you can try an idea, see what happens and try again. That freedom matters: it gives people the confidence to make something they would not have attempted alone.'],['What I brought together','I brought filmmakers, engineers and technology partners together, with tools to explore, a shared deadline and a real screening to work towards. Filmmakers brought story and taste. Engineers helped them discover new ways to realise those ideas. My job was to make that collaboration possible.'],['Why the cinema matters','A deadline turns experiments into decisions. An audience gives those decisions a purpose. Teams made films in 48 hours, and work was screened at Cinéum Cannes during festival week. Big Screen Hack gives emerging creative work a place to begin, people to develop it with and somewhere to be seen.']],links:[['About Big Screen Hack','https://www.bigscreenhack.com/'],['Film credits and screening record','https://www.bigscreenhack.com/film/lilies.html']]});
byId('creative-community').images.push({src:'assets/bsh-shared-imagination.png',alt:'Conceptual illustration: filmmakers and engineers around a shared workbench, a ribbon of film rising to the Big Screen Hack screen and a cinema audience. AI-generated artwork, not an event photograph.'});
records.push({id:'video-foundations',title:'Building generative video before the boom',category:'Generative video',role:'Founder / Yepic AI',images:[{src:'assets/aaron-portrait.jpg',alt:'Aaron Jones'}],body:[['Seeing it early','I began working on AI video in 2019, exploring what generative models could make possible for communication.'],['Building the technology','At Yepic, we developed video generation and live video communication products. Our work brought together researchers and engineers to turn emerging models into usable systems.'],['Beyond the demo','By 2022, OVHcloud’s account documented more than a million videos generated with Yepic Studio, alongside work on simultaneous video translation.']],links:[['OVHcloud’s 2022 account','https://www.ovhcloud.com/sites/default/files/casestudy/casestudy-yepic-ovhcloud-en-022022_1_1.pdf']]});
records.push({id:'world-models',title:'From watching a world to interacting with it',category:'Current research',role:'Real-time video / World models / Research and product development',body:[['What I’m exploring','I’m working on world models and real-time video: experiences that can change in response to what someone does, rather than a clip they simply watch.'],['Why now','My work has moved from visual recognition to video generation to live interaction. World models are the next part of that journey.'],['What I want to build','Tools that let people explore an idea together, see different possibilities and shape the direction while it is still taking form. This is active research and development, not a finished capability claim.']],links:[['My real-time video research collection','https://github.com/yepicaiaaron/awesome-realtime-video-generation']]});
fs.writeFileSync('dist/js/collection-data.js','window.portfolioCollection='+JSON.stringify(records)+';');
