import fs from 'node:fs';
const changes = [
['Meet your builder', 'About me'],
['You bring<br>the <em>what if.</em><br>I build it.', "I love building<br><em>things that haven’t<br>been built before.</em>"],
["I'm Aaron. A creative technologist and research engineer who loves the difficult bit: making ambitious ideas work in the real world.", "Most of my work has been in real-time AI: avatars you can talk to, video models, and the systems that make them work. I’m a research engineer and a creative technologist. I write the code, work with the people involved, and get it delivered."],
['What if?', 'Real time.'],
['From the first idea<br>to the live experience.', 'I like figuring out<br>how to make it work.'],
['Make your AI<br><em>mean something.</em>', 'I’m excited about<br><em>real-time creativity.</em>'],
['A conversation people remember. A complicated system anyone can use. A team confident enough to build what comes next.', 'Imagine a whole team exploring ideas together, seeing them take shape and changing direction as they go. That’s what I’m working towards with StoryMachine.'],
['I connect frontier research, creative direction and the engineering that gets you there.', 'Generating more isn’t the point. It’s being able to explore your options sooner, so you can work out what you actually want to make.'],
['For your audience', 'The way I want to create'],
['Experiences<br>worth talking about.', 'Real-time and<br>interactive.'],
['For your organisation', 'With other people'],
['AI that moves<br>beyond the demo.', 'Immersive and<br>collaborative.'],
['Proof / A conversation with Rory', 'Rory Sutherland at MADFest'],
['03 / Make people feel something', '03 / Rory Sutherland at MADFest'],
['A confession.<br>A conversation.<br><em>A digital Rory.</em>', 'We built Rory<br><em>a confessional.</em>'],
['How do you make an AI activation people actually want to try?', 'Marketers could confess their marketing sins to a digital Rory Sutherland. He answered in his voice, in his style. He even vaped.'],
["At MADFest, we brought Rory Sutherland's confessional idea to life — his voice, his humour, his likeness. Designed, built and delivered in five days.", 'It was Rory’s idea. I secured his involvement, and we designed, built and delivered the whole thing in five days. Hundreds of people came to talk to him.'],
['An impossible deadline.<br>A very real experience.', 'Five days to design,<br>build and deliver it.'],
['Proof / An event that talks back', 'London Tech Week'],
['04 / Make information human', '04 / London Tech Week'],
['What if your event<br><em>could talk back?</em>', 'The hosts couldn’t<br>be on every stage.<br><em>Their AI versions could listen.</em>'],
['At London Tech Week, AI hosts could discuss what had just been said on stage — and help visitors find their next conversation.', 'We made interactive AI versions of Oli Barrett and Susannah Streeter, and fed them live transcripts from the event’s stages.'],
['I connected live event knowledge to conversational versions of Oli Barrett and Susannah Streeter.', 'You could ask about a talk you’d missed, discuss what a speaker had said, or find a session that interested you. I worked on connecting that live knowledge to the conversations.'],
['The right knowledge.<br>At the right moment.', 'Ask about something<br>that just happened on stage.'],
['Proof / Technology with a human purpose', 'Projects in Saudi Arabia and Oman'],
['05 / Why it matters', '05 / Saudi Arabia and Oman'],
['Technology is<br>only the start.<br><em>People are the point.</em>', 'Your first interview<br><em>shouldn’t be your<br>first practice.</em>'],
['In Saudi Arabia, an AI interview coach gave students a place to practise their first job interview. In Oman, AI video helped deliver election information at national scale.', 'Imagine leaving university having never had a job interview. For SDAIA and King Saud University, we built an AI coach that let students practise and get feedback. Over a hundred students tried it.<br><br>In a separate project, I built the AI video workflow for Oman’s Shura Council election coverage.'],
['Under the surface / Built to work', 'Abu Dhabi Aviation and Oracle'],
['06 / The engineering behind it', '06 / Abu Dhabi Aviation and Oracle'],
["The hard part?<br><em>That's my part.</em>", 'It all had to run<br><em>on their hardware.</em>'],
['For Abu Dhabi Aviation with Oracle, I led and coded an on-premise system that turned legacy data into spoken answers and interactive charts, with permission-aware access.', 'Airport staff needed years of experience with short codes just to ask their systems a simple question. I led and coded an interface that let them ask in ordinary language, with charts and an avatar explaining the answer.'],
['Speech, language, voice and video — optimized together for local hardware.', 'We couldn’t rely on cloud services. Speech recognition, the language model, voice and video all had to run locally, with different access permissions. Getting that responsive on an L40 was a proper engineering challenge.'],
['What I could do for you', 'Speaking, consulting and teaching'],
['07 / Bring the possibilities to your people', '07 / Speaking, consulting and teaching'],
['Leave your team<br><em>seeing differently.</em>', 'I love it when<br><em>someone gets it.</em>'],
["Book a talk grounded in things I've built. Give your leaders a clear AI strategy. Help your team go from curious to capable.", 'Someone arrives unsure how to use ChatGPT, and leaves understanding how to build an agent or automate part of their work. Seeing that click is one of the most satisfying parts of what I do.'],
['Through General Purpose, I combine executive coaching with practical training in AI engineering and creative workflows.', 'As General Purpose’s lead AI engineering consultant, I help leaders decide where to start, then teach their teams how to do it. I also speak about real-time AI and storytelling, using examples from my own work.'],
['Research depth.<br>Real-world experience.<br>Practical understanding.', 'DeepFest × LEAP<br>Saudi Arabia, 2026'],
['Your next chapter', 'Work with me'],
['08 / What shall we build?', '08 / Work with me'],
['Your next<br><em>“what if”</em><br>starts here.', 'Tell me what<br><em>you’re working on.</em>'],
["I'm building towards real-time, collaborative creativity with StoryMachine. What difficult, interesting problem are you trying to solve?", 'I’m interested in real-time AI video projects, speaking opportunities and roles where I can build something genuinely new. If you’ve got a difficult problem and think I could help, I’d like to hear about it.'],
['What<br>next?', 'Let’s talk.'],
['Which possibility would you explore?', 'What are you interested in?'],
['An AI-enabled team', 'AI training for my team'],
['Scroll to unfold the story', 'Scroll to continue']
];
let html=fs.readFileSync('cinema.html','utf8');
for(const [from,to] of changes){if(!html.includes(from))throw new Error('Missing text: '+from);html=html.replaceAll(from,to)}
fs.writeFileSync('cinema.html',html);
